unbind C-b
set -g prefix C-z
bind-key C-z send-prefix

set -g default-terminal "tmux-256color"

set -g bell-action none
set -g set-clipboard off
set -g visual-bell off
set -g history-limit 3000

set -g status on
set -g status-position bottom
set -g status-left-length 0
set -g status-right-length 0
set -g window-status-format "#I #W"
set -g window-status-current-format "#[bold]#I #W#[default]"

bind-key l choose-window
bind-key ] paste-buffer
bind-key U send-keys "export LANG=en_US.UTF-8" C-m

bind-key c new-window
bind-key x switch-client -T region
bind-key -T region 2 split-window -v
bind-key -T region 3 split-window -h
bind-key -T region 1 kill-pane -a
bind-key -T region 0 kill-pane
bind-key -T region o select-pane -t :.+
bind-key -T region ^ resize-pane -Z
bind-key -T region Escape switch-client -T prefix
bind-key -T region q switch-client -T prefix
